[package]
name = "guessing_game"
version = "0.1.0"
authors = ["imgomez0127 <ianm0127@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
rand = "0.5.5"
=======

rand="0.3.14"
>>>>>>> 4f6b902362828597cd1d36211a63c249a6bc341d
